package serviceServeur;


/**
* serviceServeur/ServiceServeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServiceServeur.idl
* mardi 20 mars 2018 15 h 52 CET
*/

public interface ServiceServeur extends ServiceServeurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServiceServeur
