package serviceServeur;


/**
* serviceServeur/ServiceServeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./serviceServeur.idl
* mercredi 21 mars 2018 09 h 02 CET
*/

public interface ServiceServeurOperations 
{
  void sendMessage (String message, serviceServeur.Utilisateur utilisateur);
  boolean authenticate (String nom, String motDePasse, serviceServeur.UtilisateurHolder utilisateur);
} // interface ServiceServeurOperations
