package serviceServeur;


/**
* serviceServeur/ServiceServeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServiceServeur.idl
* mardi 20 mars 2018 16 h 34 CET
*/

public interface ServiceServeurOperations 
{
  void sendMessage (String message, serviceServeur.UtilisateurHolder utilisateur);
  boolean authenticate (String nom, String motDePasse, serviceServeur.UtilisateurHolder utilisateur);
} // interface ServiceServeurOperations
