package serviceServeur;


/**
* serviceServeur/UtilisateurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./serviceServeur.idl
* mercredi 21 mars 2018 09 h 02 CET
*/

public interface UtilisateurOperations 
{
  String getName ();
  void setName (String name);
  String getPassword ();
  void setPassword (String password);
  void afficher (String message);
} // interface UtilisateurOperations
