package corbaInterface;


/**
* corbaInterface/_ServiceServeurStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./serviceServeur.idl
* mercredi 21 mars 2018 09 h 49 CET
*/

public class _ServiceServeurStub extends org.omg.CORBA.portable.ObjectImpl implements corbaInterface.ServiceServeur
{

  public void sendMessage (corbaInterface.MessageType messageType, String message, corbaInterface.Utilisateur utilisateur)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sendMessage", true);
                corbaInterface.MessageTypeHelper.write ($out, messageType);
                $out.write_string (message);
                corbaInterface.UtilisateurHelper.write ($out, utilisateur);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sendMessage (messageType, message, utilisateur        );
            } finally {
                _releaseReply ($in);
            }
  } // sendMessage

  public boolean authenticate (String nom, String motDePasse, corbaInterface.Utilisateur utilisateur)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("authenticate", true);
                $out.write_string (nom);
                $out.write_string (motDePasse);
                corbaInterface.UtilisateurHelper.write ($out, utilisateur);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return authenticate (nom, motDePasse, utilisateur        );
            } finally {
                _releaseReply ($in);
            }
  } // authenticate

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corbaInterface/ServiceServeur:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServiceServeurStub
