package corbaInterface;


/**
* corbaInterface/MessageType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./serviceServeur.idl
* mercredi 21 mars 2018 10 h 47 CET
*/

public class MessageType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static corbaInterface.MessageType[] __array = new corbaInterface.MessageType [__size];

  public static final int _authenticate = 0;
  public static final corbaInterface.MessageType authenticate = new corbaInterface.MessageType(_authenticate);
  public static final int _message = 1;
  public static final corbaInterface.MessageType message = new corbaInterface.MessageType(_message);
  public static final int _joinRoom = 2;
  public static final corbaInterface.MessageType joinRoom = new corbaInterface.MessageType(_joinRoom);
  public static final int _leaveRoom = 3;
  public static final corbaInterface.MessageType leaveRoom = new corbaInterface.MessageType(_leaveRoom);
  public static final int _quit = 4;
  public static final corbaInterface.MessageType quit = new corbaInterface.MessageType(_quit);

  public int value ()
  {
    return __value;
  }

  public static corbaInterface.MessageType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected MessageType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class MessageType
