package corbaInterface;


/**
* corbaInterface/MessageTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./serviceServeur.idl
* mercredi 21 mars 2018 09 h 49 CET
*/

abstract public class MessageTypeHelper
{
  private static String  _id = "IDL:corbaInterface/MessageType:1.0";

  public static void insert (org.omg.CORBA.Any a, corbaInterface.MessageType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corbaInterface.MessageType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (corbaInterface.MessageTypeHelper.id (), "MessageType", new String[] { "authenticate", "message"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corbaInterface.MessageType read (org.omg.CORBA.portable.InputStream istream)
  {
    return corbaInterface.MessageType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corbaInterface.MessageType value)
  {
    ostream.write_long (value.value ());
  }

}
