package corbaInterface;


/**
* corbaInterface/ServiceServeurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./serviceServeur.idl
* mercredi 21 mars 2018 09 h 12 CET
*/

public abstract class ServiceServeurPOA extends org.omg.PortableServer.Servant
 implements corbaInterface.ServiceServeurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendMessage", new java.lang.Integer (0));
    _methods.put ("authenticate", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corbaInterface/ServiceServeur/sendMessage
       {
         String message = in.read_string ();
         corbaInterface.Utilisateur utilisateur = corbaInterface.UtilisateurHelper.read (in);
         this.sendMessage (message, utilisateur);
         out = $rh.createReply();
         break;
       }

       case 1:  // corbaInterface/ServiceServeur/authenticate
       {
         String nom = in.read_string ();
         String motDePasse = in.read_string ();
         corbaInterface.Utilisateur utilisateur = corbaInterface.UtilisateurHelper.read (in);
         boolean $result = false;
         $result = this.authenticate (nom, motDePasse, utilisateur);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corbaInterface/ServiceServeur:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServiceServeur _this() 
  {
    return ServiceServeurHelper.narrow(
    super._this_object());
  }

  public ServiceServeur _this(org.omg.CORBA.ORB orb) 
  {
    return ServiceServeurHelper.narrow(
    super._this_object(orb));
  }


} // class ServiceServeurPOA
