package corbaInterface;

/**
* corbaInterface/ServiceServeurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./corbaInterface.idl
* jeudi 22 mars 2018 10 h 35 CET
*/

public final class ServiceServeurHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaInterface.ServiceServeur value = null;

  public ServiceServeurHolder ()
  {
  }

  public ServiceServeurHolder (corbaInterface.ServiceServeur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaInterface.ServiceServeurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaInterface.ServiceServeurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaInterface.ServiceServeurHelper.type ();
  }

}
