package corbaInterface;


/**
* corbaInterface/ServiceServeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./serviceServeur.idl
* mercredi 21 mars 2018 09 h 49 CET
*/

public interface ServiceServeurOperations 
{
  void sendMessage (corbaInterface.MessageType messageType, String message, corbaInterface.Utilisateur utilisateur);
  boolean authenticate (String nom, String motDePasse, corbaInterface.Utilisateur utilisateur);
} // interface ServiceServeurOperations
