package corbaInterface;


/**
* corbaInterface/UtilisateurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./corbaInterface.idl
* jeudi 22 mars 2018 10 h 35 CET
*/

public interface UtilisateurOperations
{
  String getName ();
  void setName (String name);
  String getPassword ();
  void setPassword (String password);
  void afficher (String message);
} // interface UtilisateurOperations
