package serviceServeur;

/**
* serviceServeur/ServiceServeurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServiceServeur.idl
* mardi 20 mars 2018 14 h 50 CET
*/

public final class ServiceServeurHolder implements org.omg.CORBA.portable.Streamable
{
  public serviceServeur.ServiceServeur value = null;

  public ServiceServeurHolder ()
  {
  }

  public ServiceServeurHolder (serviceServeur.ServiceServeur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serviceServeur.ServiceServeurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serviceServeur.ServiceServeurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serviceServeur.ServiceServeurHelper.type ();
  }

}
