package corbaInterface;


/**
* corbaInterface/ServiceServeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./corbaInterface.idl
* jeudi 22 mars 2018 17 h 34 CET
*/

public interface ServiceServeurOperations 
{
  boolean createAccount (corbaInterface.Utilisateur utilisateur);
  boolean authenticate (corbaInterface.Utilisateur utilisateur);
  String getRoomList (corbaInterface.Utilisateur utilisateur);
  boolean createRoom (String roomName, corbaInterface.Utilisateur utilisateur);
  boolean joinRoom (String roomName, corbaInterface.Utilisateur utilisateur);
  void sendMessage (String message, corbaInterface.Utilisateur utilisateur);
  String getHistory (corbaInterface.Utilisateur utilisateur);
  void quit (corbaInterface.Utilisateur utilisateur);
} // interface ServiceServeurOperations
