package corbaInterface;


/**
* corbaInterface/ServiceServeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./serviceServeur.idl
* mercredi 21 mars 2018 09 h 49 CET
*/

public interface ServiceServeur extends ServiceServeurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServiceServeur
