package corbaInterface;


/**
* corbaInterface/ServiceServeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./corbaInterface.idl
* jeudi 22 mars 2018 17 h 34 CET
*/

public interface ServiceServeur extends ServiceServeurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServiceServeur
