package corbaInterface;


/**
* corbaInterface/ServiceServeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./corbaInterface.idl
* mercredi 21 mars 2018 11 h 54 CET
*/

public interface ServiceServeur extends ServiceServeurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServiceServeur
