package corbaInterface;


/**
* corbaInterface/Utilisateur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./corbaInterface.idl
* jeudi 22 mars 2018 10 h 35 CET
*/

public interface Utilisateur extends UtilisateurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Utilisateur
