package corbaInterface;

/**
* corbaInterface/UtilisateurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./corbaInterface.idl
* jeudi 22 mars 2018 10 h 35 CET
*/

public final class UtilisateurHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaInterface.Utilisateur value = null;

  public UtilisateurHolder ()
  {
  }

  public UtilisateurHolder (corbaInterface.Utilisateur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaInterface.UtilisateurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaInterface.UtilisateurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaInterface.UtilisateurHelper.type ();
  }

}
