module serviceServeur {
    interface Utilisateur {
    };

    interface ServiceServeur {
        void sendMessage(in string message, inout Utilisateur utilisateur);
        boolean authenticate(in string nom, in string motDePasse, inout Utilisateur utilisateur);
    };
};