package serviceServeur;


/**
* serviceServeur/ServiceServeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServiceServeur.idl
* mardi 20 mars 2018 15 h 52 CET
*/

public interface ServiceServeurOperations 
{
  int add (int a, int b);
  void shutdown ();
} // interface ServiceServeurOperations
