package serviceServeur;


/**
* serviceServeur/Utilisateur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServiceServeur.idl
* mardi 20 mars 2018 16 h 34 CET
*/

public interface Utilisateur extends UtilisateurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Utilisateur
